export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND';
export const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT';
